ALTER TABLE users 
ADD COLUMN body_height INTEGER DEFAULT 0;

ALTER TABLE users
ADD COLUMN last_login TEXT DEFAULT "2025-05-14 01:10";

ALTER TABLE users
ADD COLUMN retries INTEGER DEFAULT 0;

CREATE TABLE weights (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    userid INTEGER NOT NULL,
    body_weight INTEGER DEFAULT 0 );

CREATE INDEX user2 ON weights (userid);

